# Generated by Django 3.0.6 on 2020-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naresh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='intro',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
