# Generated by Django 3.0.6 on 2020-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naresh', '0002_auto_20200607_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='notes',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
